import "@/styles/globals.css"

import type { Metadata } from "next"
import {
  inter,
  nanumMyeongjo,
  playfairDisplay,
  sourceSerif,
} from "@/assets/fonts"

import { navConfig } from "@/config/nav"
import { SiteFooter } from "@/components/site-footer"
import { SiteHeader } from "@/components/site-header"

export const metadata: Metadata = {
  title: "E. I. Morrow Co., Inc.",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`min-h-screen bg-background font-sans antialiased ${nanumMyeongjo.variable} ${inter.variable}`}
      >
        <div className="relative flex min-h-screen flex-col">
          <SiteHeader />
          <main className="flex-1 bg-slate-300">{children}</main>
          <SiteFooter items={navConfig.navItems} />
        </div>
      </body>
    </html>
  )
}
